name: Hello World

on:
  push:
    branches:
      - main    # run only when pushing to 'main'

jobs:
  hello-job:              # ✅ this is the job name
    runs-on: ubuntu-latest

    steps:
      - name: Echo text
        run: echo "Hello, world!"

